name: Build Tailwind CSS

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Tailwind CSS and HTML
        run: npm run build

      - name: List docs folder (debug)
        run: ls -lh docs/

      - name: Commit and push compiled docs
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull --rebase --autostash
          git add docs/
          git commit -m "Build Tailwind output to docs/" || echo "No changes"
          git push
